FROM nginx:alpine

RUN apk add --no-cache gettext

# disable ipv6 auto injection
RUN echo "" > /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

# delete default nginx conf
RUN rm -f /etc/nginx/conf.d/default.conf

COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template
COPY entrypoint.railway.sh /docker-entrypoint.d/00-process-template.sh
RUN chmod +x /docker-entrypoint.d/00-process-template.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
